info:
  component: stationerycontrol-delivery-api

server:
  port: 8084
  servlet:
    context-path: /api

spring:
  application:
    name: stationerycontrol-delivery-api
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

feign:
  client:
    config:
      default:
        connectTimeout: 12000
        readTimeout: 12000
        loggerLevel: basic
